### ISSUE TITLE
Examples outdated

### ISSUE THREAD

**Issue by Daandelange** [kylemcdonald/ofxAutostereogram#1]
Hey Kyle,
I'm getting a bunch of errors on both of the examples using OSX 10.6.8, XCode 4.0.2 and oFX 0.8.0. The ofxAutostereogram library is in the oFX addons folder. Looks like there are a few path errors that cause various other compilation errors.
I'm a newbie to oFX but all other examples I've tried are working so far. Would be great to include functional out-of-the-box examples! :+1:

**Comment by kylemcdonald** [comment]
fixed. also, uploading a video to vimeo now about how to do this for yourself in case you or anyone else runs into this.

**Comment by Daandelange** [comment]
Great, thank you :)
